# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3061b9a109f1b6c3f7c6921301d18488147e17b9de209303478bfd9b509b419f5067da40a9e759c71669f45fb1d4798f431ed865cb58edd0baad832c581efafb

test:
  secret_key_base: be667de59083fbd148da66260bee3c6b4f5caebb840b3bc21bb9293559a2ea5436163af7e00f6ca274fa9a172bdce0e83feee7a4680d5b144d93e8649026498e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
